service: figlet-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region:  us-west-2
 
functions:
  testFiglet:
    handler: index.handler
    layers:
      - arn:aws:lambda:us-west-2:XXXXXXX:layer:figlet:1
  